"""empty message

Revision ID: 137e07e520b3
Revises: 
Create Date: 2024-03-08 18:25:19.424754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137e07e520b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_entity')
    # ### end Alembic commands ###
