name: Python Application CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Build Docker base image "Builder" for next stage
      run: docker build --build-arg INSTALL_PYTHON_VERSION=3.11 --target builder -t insta_cloud:builder -f instacloud_core/Dockerfile instacloud_core/

    - name: Build Docker image as final Artifact
      run: docker build --build-arg INSTALL_PYTHON_VERSION=3.11 --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}  --target production -t insta_cloud:production -f instacloud_core/Dockerfile instacloud_core/

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Artifact to Docker Hub
      run: docker push insta_cloud:production
