name: Python Application CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r instacloud_core/requirements/prod.txt

    - name: Build Docker image Builder for next stage
      run: docker build --target builder -t insta_cloud:builder -f Dockerfile .

    - name: Build Docker image as final Artifact
      run: docker build --target production -t insta_cloud:production -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Artifact to Docker Hub
      run: docker push insta_cloud:production
